[project]
name = "mdz"
version = "0.1.0"
description = ""
authors = [
    {name = "ivansantiagojr",email = "ivansantiago.junior@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
]

[tool.poetry]
include = [
    { path = "src/", format = "sdist" },
    { path = "mdz/*.so", format = "wheel" }
]

[tool.poetry.build]
script = "build.py"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
ziggy-pydust = {git = "https://github.com/ivansantiagojr/ziggy-pydust", rev = "allow-third-party-modules"}

[tool.pydust]
self_managed = true

[build-system]
requires = [
    "poetry-core>=2.0.0,<3.0.0",
    "ziggy-pydust @ git+https://github.com/ivansantiagojr/ziggy-pydust#allow-third-party-modules"
    ]
build-backend = "poetry.core.masonry.api"
